LIB_NAME = editstat

# relative path from here to main build directory
REL_ROOT=../../../build/linux/

DIR_SRC_ROOT=$(DIR_EDITSTAT)

# include procedure makefile
include $(DIR_C_MAKE_INCLUDE)make_proc