# short procedure name, used for build output, folder, test names, etc.
LIB_NAME = determin

# relative path from here to main build directory
REL_ROOT=../../../build/linux/

DIR_SRC_ROOT=$(DIR_DETERMIN)

# include procedure makefile
include $(DIR_C_MAKE_INCLUDE)make_proc