LIB_NAME = errorloc

# relative path from here to main build directory
REL_ROOT=../../../build/linux/

DIR_SRC_ROOT=$(DIR_ERRORLOC)

# include procedure makefile
include $(DIR_C_MAKE_INCLUDE)make_proc