#ifndef EI_ESTIMATOR_H
#define EI_ESTIMATOR_H

#include "EI_Common.h"
#include "EI_DataTable.h"
#include "EI_EstimatorSpec.h"

/*
something to prevent clash with real variable name
*/
#define EIM_BETA_PREFIX "1BETA"

CLASS_DECLSPEC EIT_BOOLEAN EI_AreEFRequestedWithParameters (EIT_ESTIMATORSPEC_LIST *);
CLASS_DECLSPEC EIT_BOOLEAN EI_AreHistVariablesRequested (EIT_ESTIMATORSPEC_LIST *);
CLASS_DECLSPEC EIT_BOOLEAN EI_AreLRRequested (EIT_ESTIMATORSPEC_LIST *);
CLASS_DECLSPEC EIT_BOOLEAN EI_AreParametersRequested (EIT_ESTIMATORSPEC_LIST *);
CLASS_DECLSPEC EIT_BOOLEAN EI_AreRandomErrorsRequested (EIT_ESTIMATORSPEC_LIST *);
CLASS_DECLSPEC void EI_ComputeAverages (EIT_ESTIMATORSPEC_LIST *, EIT_DATATABLE *);
CLASS_DECLSPEC EIT_RETURNCODE EI_ComputeBetas (EIT_ESTIMATORSPEC_LIST *,
    EIT_DATATABLE *);
CLASS_DECLSPEC EIT_RETURNCODE EI_DoEstimation (EIT_ESTIMATORSPEC_LIST *, EIT_SYMBOL **,
    EIT_DATATABLE *);
CLASS_DECLSPEC EIT_RETURNCODE EI_DoEstimationRejectNegative (EIT_ESTIMATORSPEC_LIST *,
    EIT_SYMBOL **, EIT_DATATABLE *);
CLASS_DECLSPEC char * EI_EstimatorFormatFormula (char *, char *, char *, char *);
CLASS_DECLSPEC void EI_Reactivate (EIT_ESTIMATORSPEC_LIST *);
CLASS_DECLSPEC void EI_SetUpEstimators (EIT_ESTIMATORSPEC_LIST *, char **, int, char **,
    int, EIT_BOOLEAN, EIT_BOOLEAN);
CLASS_DECLSPEC void EI_ValidateCriteria (EIT_ESTIMATORSPEC_LIST *, int);
CLASS_DECLSPEC EIT_RETURNCODE EI_ValidateEstimator (EIT_ESTIMATORSPEC_LIST *,
    EIT_SYMBOL **);
CLASS_DECLSPEC EIT_RETURNCODE EI_ValidateWeightAndVarianceVariables (
    EIT_ESTIMATORSPEC_LIST *, EIT_DATATABLE *);

#endif
